---
- name: Configure PHP
  ansible.builtin.template:
    src: templates/etc/php/8.3/fpm/conf.d/custom.ini.j2
    dest: /etc/php/8.3/fpm/conf.d/custom.ini
    owner: root
    group: root
    mode: "0644"
  notify: Restart PHP-FPM
  tags: [php]

- name: Download Composer installer
  ansible.builtin.get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: "0755"
  tags: [php]

- name: Install Composer globally
  ansible.builtin.command: >
    php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
  tags: [php]
